apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/name: infrastructure
    app.kubernetes.io/part-of: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure components project (monitoring, ingress, etc.)

  # Allowed source repositories
  sourceRepos:
    - "https://github.com/org/python-api-base.git"
    - "https://charts.bitnami.com/bitnami"
    - "https://prometheus-community.github.io/helm-charts"
    - "https://grafana.github.io/helm-charts"
    - "https://kubernetes.github.io/ingress-nginx"

  # Allowed destination clusters and namespaces
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: sealed-secrets
      server: https://kubernetes.default.svc

  # Allow specific cluster-scoped resources for infrastructure
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration

  # Allow all namespace-scoped resources
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  # Orphaned resources monitoring
  orphanedResources:
    warn: true

  # RBAC roles
  roles:
    - name: infra-admin
      description: Infrastructure admin access
      policies:
        - p, proj:infrastructure:infra-admin, applications, *, infrastructure/*, allow
      groups:
        - infra-admins

    - name: infra-viewer
      description: Infrastructure read-only access
      policies:
        - p, proj:infrastructure:infra-viewer, applications, get, infrastructure/*, allow
        - p, proj:infrastructure:infra-viewer, logs, get, infrastructure/*, allow
      groups:
        - developers
        - viewers
