apiVersion: batch/v1
kind: Job
metadata:
  name: smoke-test-postsync
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: smoke-test
    app.kubernetes.io/part-of: python-api-base
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "5"
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smoke-test
    spec:
      restartPolicy: Never
      containers:
        - name: smoke-test
          image: curlimages/curl:8.5.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Running smoke tests..."
              
              # Wait for service to be ready
              sleep 10
              
              # Health check
              echo "Checking liveness endpoint..."
              curl -sf http://python-api-base:8000/health/live || exit 1
              
              # Readiness check
              echo "Checking readiness endpoint..."
              curl -sf http://python-api-base:8000/health/ready || exit 1
              
              # API version check
              echo "Checking API version..."
              curl -sf http://python-api-base:8000/api/v1/version || exit 1
              
              echo "All smoke tests passed!"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      securityContext:
        fsGroup: 1000
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-fail-notification
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: sync-fail-notification
    app.kubernetes.io/part-of: python-api-base
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sync-fail-notification
    spec:
      restartPolicy: Never
      containers:
        - name: notify
          image: curlimages/curl:8.5.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              echo "Sync failed - sending notification..."
              # Additional failure handling can be added here
              # e.g., webhook calls, cleanup tasks
              echo "Failure notification sent"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
