apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-presync
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: db-migration
    app.kubernetes.io/part-of: python-api-base
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-5"
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db-migration
    spec:
      restartPolicy: Never
      serviceAccountName: python-api-base
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              echo "Running database migrations..."
              alembic upgrade head
              echo "Migrations completed successfully"
          env:
            - name: DATABASE__URL
              valueFrom:
                secretKeyRef:
                  name: python-api-base-secrets
                  key: database-url
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      securityContext:
        fsGroup: 1000
