apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kepler
  labels:
    app.kubernetes.io/name: kepler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kepler
subjects:
  - kind: ServiceAccount
    name: kepler
    namespace: kepler-system
