apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kepler
  labels:
    app.kubernetes.io/name: kepler
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
      - namespaces
      - configmaps
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - nodes/metrics
      - nodes/proxy
      - nodes/stats
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs: ["get", "list", "watch"]
