apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-api-base
  labels:
    app.kubernetes.io/name: python-api-base
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: python-api-base
  labels:
    app.kubernetes.io/name: python-api-base
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: python-api-base
  labels:
    app.kubernetes.io/name: python-api-base
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: python-api-base
subjects:
  - kind: ServiceAccount
    name: python-api-base
