apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-api-base-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: python-api-base-dev
    app.kubernetes.io/part-of: python-api-base
    environment: dev
  annotations:
    # Image Updater annotations
    argocd-image-updater.argoproj.io/image-list: api=ghcr.io/org/python-api-base
    argocd-image-updater.argoproj.io/api.update-strategy: semver
    argocd-image-updater.argoproj.io/api.allow-tags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+(-dev\.[0-9]+)?$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    # Notifications
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: dev-deployments
    notifications.argoproj.io/subscribe.on-sync-failed.slack: dev-alerts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: python-api-base

  source:
    repoURL: https://github.com/org/python-api-base.git
    targetRevision: HEAD
    path: deployments/helm/api
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
      parameters:
        - name: image.tag
          value: latest

  destination:
    server: https://kubernetes.default.svc
    namespace: python-api-dev

  # Auto-sync with self-heal for dev environment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignore differences
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

  # Revision history limit
  revisionHistoryLimit: 10
