apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-api-base-knative-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: python-api-base
    app.kubernetes.io/component: knative
    environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: python-api-base
  source:
    repoURL: https://github.com/org/python-api-base
    targetRevision: HEAD
    path: deployments/knative/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: my-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-api-base-knative-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: python-api-base
    app.kubernetes.io/component: knative
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: python-api-base
  source:
    repoURL: https://github.com/org/python-api-base
    targetRevision: HEAD
    path: deployments/knative/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: my-api-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-api-base-knative-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: python-api-base
    app.kubernetes.io/component: knative
    environment: development
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: python-api-base
  source:
    repoURL: https://github.com/org/python-api-base
    targetRevision: HEAD
    path: deployments/knative/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: my-api-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
