# SealedSecret templates for Python API Base
# These templates show the structure - actual secrets should be sealed using kubeseal

---
# Database credentials template
# To seal: kubeseal --format yaml < db-secret.yaml > db-sealedsecret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: python-api-base-db-credentials
  namespace: python-api-prod
  labels:
    app.kubernetes.io/name: python-api-base
    app.kubernetes.io/component: database
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  encryptedData:
    # These values should be encrypted using kubeseal
    # Example: echo -n "mypassword" | kubeseal --raw --namespace python-api-prod --name python-api-base-db-credentials
    database-url: AgBy8hXX...  # Encrypted value placeholder
    database-username: AgBy8hXX...  # Encrypted value placeholder
    database-password: AgBy8hXX...  # Encrypted value placeholder
  template:
    metadata:
      name: python-api-base-db-credentials
      namespace: python-api-prod
      labels:
        app.kubernetes.io/name: python-api-base
        app.kubernetes.io/component: database
    type: Opaque

---
# API keys template
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: python-api-base-api-keys
  namespace: python-api-prod
  labels:
    app.kubernetes.io/name: python-api-base
    app.kubernetes.io/component: api-keys
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  encryptedData:
    jwt-secret: AgBy8hXX...  # Encrypted value placeholder
    redis-password: AgBy8hXX...  # Encrypted value placeholder
    encryption-key: AgBy8hXX...  # Encrypted value placeholder
  template:
    metadata:
      name: python-api-base-api-keys
      namespace: python-api-prod
      labels:
        app.kubernetes.io/name: python-api-base
        app.kubernetes.io/component: api-keys
    type: Opaque

---
# External services credentials template
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: python-api-base-external-services
  namespace: python-api-prod
  labels:
    app.kubernetes.io/name: python-api-base
    app.kubernetes.io/component: external-services
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  encryptedData:
    kafka-password: AgBy8hXX...  # Encrypted value placeholder
    elasticsearch-password: AgBy8hXX...  # Encrypted value placeholder
    minio-access-key: AgBy8hXX...  # Encrypted value placeholder
    minio-secret-key: AgBy8hXX...  # Encrypted value placeholder
  template:
    metadata:
      name: python-api-base-external-services
      namespace: python-api-prod
      labels:
        app.kubernetes.io/name: python-api-base
        app.kubernetes.io/component: external-services
    type: Opaque
