apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: sealed-secrets-controller
    app.kubernetes.io/part-of: infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure

  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.14.2
    helm:
      releaseName: sealed-secrets
      values: |
        fullnameOverride: sealed-secrets-controller
        
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          fsGroup: 65534
        
        containerSecurityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        
        metrics:
          serviceMonitor:
            enabled: true
            namespace: monitoring
        
        # Key renewal period (30 days)
        keyrenewperiod: 720h

  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
