apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # Default policy for authenticated users
  policy.default: role:readonly

  # RBAC policies following least-privilege principle
  policy.csv: |
    # Admin role - full access
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, gpgkeys, *, *, allow
    p, role:admin, logs, *, *, allow
    p, role:admin, exec, *, */*, allow
    
    # Developer role - limited access
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, sync, */*, allow
    p, role:developer, applications, action/*, */*, allow
    p, role:developer, logs, get, */*, allow
    p, role:developer, repositories, get, *, allow
    p, role:developer, projects, get, *, allow
    
    # Readonly role - view only
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, projects, get, *, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, logs, get, */*, allow
    
    # Project-specific roles
    p, proj:python-api-base:developer, applications, get, python-api-base/*, allow
    p, proj:python-api-base:developer, applications, sync, python-api-base/*, allow
    p, proj:python-api-base:developer, applications, action/*, python-api-base/*, allow
    p, proj:python-api-base:developer, logs, get, python-api-base/*, allow
    
    p, proj:python-api-base:viewer, applications, get, python-api-base/*, allow
    p, proj:python-api-base:viewer, logs, get, python-api-base/*, allow
    
    # Group bindings
    g, admin-group, role:admin
    g, developers, role:developer
    g, viewers, role:readonly

  # Scopes for OIDC
  scopes: "[groups, email]"
