apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 1m"
    - name: direction
      value: input
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-binding
spec:
  type: bindings.kafka
  version: v1
  metadata:
    - name: brokers
      value: kafka:9092
    - name: topics
      value: events
    - name: consumerGroup
      value: python-api-bindings
    - name: authType
      value: none
    - name: direction
      value: input
