apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: /secrets/secrets.json
    - name: nestedSeparator
      value: ":"
---
# For production, use HashiCorp Vault or Kubernetes secrets
# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: vault
# spec:
#   type: secretstores.hashicorp.vault
#   version: v1
#   metadata:
#     - name: vaultAddr
#       value: http://vault:8200
#     - name: vaultToken
#       secretKeyRef:
#         name: vault-token
#         key: token
#     - name: vaultKVPrefix
#       value: dapr
