apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: python-api-base
spec:
  template:
    metadata:
      annotations:
        # Scale to zero enabled for dev
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/target: "50"
        autoscaling.knative.dev/scale-down-delay: "15s"
    spec:
      containerConcurrency: 50
      timeoutSeconds: 60
      containers:
        - name: api
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
